### ISSUE TITLE
How to make it work if Sitecore is running in a Docker container?

### ISSUE THREAD

**Issue by victorantos** [blipson89/Leprechaun#41]
How to make it work if Sitecore is running in a Docker container?

Does Leprechaun have any support for Docker environment? Thanks!

**Comment by blipson89** [comment]
What version of Sitecore are you using? Are you using Unicorn or Sitecore 10's new serialization?

Leprechaun doesn't need a connection to Sitecore at all. It reads the yaml files that Unicorn creates, which wouldn't likely be in a docker container because it needs to be in source control. 

If you're using Sitecore 10's new serialization, the process is a little different but it still will work.

**Comment by victorantos** [comment]
I am using Sitecore 10.1
I guess I am using Unicorn for syncing items, but it's a new installation so no sync have been run yet.

Let's say I would be running Unicorn sync, are those yaml be generated in Docker container? How do I get them into Visual Studio so I can run Leprechaun script as pre-build event? Thanks!

**Comment by blipson89** [comment]
That depends on how you've setup Unicorn and your containers. The Unicorn team would likely be able to help you more with that setup.

I did find a few resources on Google though that could help:
* https://sitecoremaster.com/social/how-to-configure-unicorn-for-a-solution-running-in-sitecore-docker-containers/
* https://gist.github.com/cassidydotdk/47eacabd752d7a84e7e5826531fb0f9e

Once Unicorn is setup and you can see the yaml files, the Leprechaun setup should be straightforward using the setup instructions on the readme.
